### ISSUE TITLE
What is the correct usage for this situation?

### ISSUE THREAD

**Issue by tienthanh2929** [Xezard/XConfiguration#2]
Let's say I want to load a list of the same type of object, but with different data.

For example, I have a Foo object:

```java
class Foo {
  long price;
  String identifier;
  String permission;

  public Foo(int price, String identifier, String permission) {
     // assign to variables
  }
}
```

In my config file:

```yaml
foos:
  myFoo: # identifier
    price: 100 #price
    permission: 'perm.myFoo' #permission
  myAnotherFoo:
   price: 200
   permission: 'perm.myAnotherFoo'
```

If I want to load in a traditional way, I just loop through all ``foos`` keys then create each individual ``Foo`` objects.

```java
for(String key : config.getConfigurationSection("foos").getKeys(false) {
   String identifier = key;
   String permission = config.getString("foos." + key + ".permission");
   long price = config.getLong("foos." + key + ".price");
 
   Foo foo = new Foo(price, identifier, permission);
   // proceed to store Foo somewhere else
}
```

So what is the correct usage for this situation with your plugin? Thanks!

**Comment by Xezard** [comment]
You have 2 options. Use identifier as a key in Map<String, Foo>, but identifier will not be a field in Foo class. Or not use identifier as a key to the object and just have List<Foo> in the configuration.
In this case, identifier will be a field of the Foo class.

With map:
```java
@SerializableAz("Foo")
public class Foo
implements ConfigurationSerializable {
  long price;
  String permission;

  public Foo(int price, String permission) {
     // assign to variables
  }

  // implement serialization methods
}
```
Configuration:
```java
@Getters
public class ExampleConfiguration
extends Configuration 
{
    public ExampleConfiguration(File folder)
    {
        super(folder.getAbsolutePath() + "example.yml");
    }

    @ConfigurationField("Example")
    private Map<String, Foo> foos = new HashMap<> ();
}
```
Use case:
```java
private ExampleConfiguration configuration;

configuration.getFoos().get("test"); // Receive ExampleObject by "test" key
```

With List:
```java
@SerializableAz("Foo")
public class Foo
implements ConfigurationSerializable {
  long price;
  String identifier, permission;

  public Foo(int price, String permission) {
     // assign to variables
  }

  // implement serialization methods
}
```
Configuration:
```java
@Getters
public class ExampleConfiguration
extends Configuration 
{
    public ExampleConfiguration(File folder)
    {
        super(folder.getAbsolutePath() + "example.yml");
    }

    @ConfigurationField("Example")
    private List<Foo> foos = new ArrayList<> ();
}
```
If you have "manager" for your Foo object, you can load your Foo objects in manager on plugin startup. Something like that:
```java
public class FooManager
{
    public void load(Map<String, Foo> foos) {}
}
```
```java
public class ExamplePlugin
extends JavaPlugin
{
    private ExampleConfiguration configuration = new ExampleConfiguration(this.getFolder());

    private FooManager manager = new FooManager();

    @Override
    public void onEnable()
    {
        this.configuration.load();

        this.manager.load(this.configuration.getFoos().stream().collect(Collectors.toMap(Foo::getIdentifier, Function.identity())));
    }
}
```
With that way you can have identifier like key and identifier field in your object.

**Comment by tienthanh2929** [comment]
I understand. With your example, if I want to create more key for ``foos``, I just need to ``put`` value into the Map like usual?

Assuming in ``ExampleConfiguration`` class, it has a ``addFoo`` method

```java
ExampleConfiguration exampleConfig = new ExampleConfiguration(this.getFolder())
exampleConfig.addFoo("firstFoo", new Foo(5, "firstFoo.perm");
exampleConfig.addFoo("anotherFoo", new Foo(10, "anotherFoo.perm")));

exampleConfig.load();
```

The config result should be like this?

```yaml
Example:
  firstFoo:
   permission: 'firstFoo.perm'
   price: 5
  anotherFoo:
   permission: 'anotherFoo.perm'
   price: 10
```

Thanks!

**Comment by Xezard** [comment]
Ohhh, i forgot add a saving section to wiki :D

For saving:
```java
this.configuration.getFoos().add("key", value);

this.configuration.save();
```

Generated config:
```yml
Example:
  firstFoo:
    ==: Foo
    permission: 'firstFoo.perm'
    price: 5
  anotherFoo:
    ==: Foo
    permission: 'anotherFoo.perm'
    price: 10
```

UPD: added saving section to wiki: https://github.com/Xezard/XConfiguration/wiki/Saving
